services:

  mysql:
    image: mysql:latest
    container_name: mysql-chat
    environment:
      MYSQL_ROOT_PASSWORD: maiload
      MYSQL_DATABASE: chat
      MYSQL_USER: jin
      MYSQL_PASSWORD: jin123
    ports:
      - "3306:3306"
    networks:
      - maiload
  #    volumes:
  #      - ./data/:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
      RABBITMQ_ERLANG_COOKIE: myCookie
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - maiload



#  rabbit1:
#    image: rabbitmq:3.13.3-management-alpine
#    container_name: rabbit1
#    hostname: rabbit1
#    environment:
#      RABBITMQ_DEFAULT_USER: user
#      RABBITMQ_DEFAULT_PASS: user
#    volumes:
#      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
#      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
#    entrypoint: /usr/local/bin/cluster-entrypoint.sh
#    networks:
#      - maiload
#
#  rabbit2:
#    image: rabbitmq:3.13.3-management-alpine
#    container_name: rabbit2
#    hostname: rabbit2
#    links:
#      - rabbit1
#    environment:
#      JOIN_CLUSTER_HOST: rabbit1
#    volumes:
#      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
#      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
#    entrypoint: /usr/local/bin/cluster-entrypoint.sh
#    networks:
#      - maiload
#
#  rabbit3:
#    image: rabbitmq:3.13.3-management-alpine
#    container_name: rabbit3
#    hostname: rabbit3
#    links:
#      - rabbit1
#      - rabbit2
#    environment:
#      JOIN_CLUSTER_HOST: rabbit1
#    volumes:
#      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
#      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
#    entrypoint: /usr/local/bin/cluster-entrypoint.sh
#    networks:
#      - maiload
#
#  haproxy:
#    image: haproxy:latest
#    volumes:
#      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
#    depends_on:
#      - rabbit1
#      - rabbit2
#      - rabbit3
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#      - "1936:1936"
#    networks:
#      - maiload




#  kopring:
#    restart: on-failure
#    container_name: chat-kopring
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/chat
#      SPRING_DATASOURCE_USERNAME: jin
#      SPRING_DATASOURCE_PASSWORD: jin123
#      RABBITMQ_HOST: haproxy
#      RABBITMQ_PORT: 5672
#      RABBITMQ_USERNAME: user
#      RABBITMQ_PASSWORD: user
#    depends_on:
#      - mysql
#      - haproxy
#    networks:
#      - maiload

networks:
  maiload:
    driver: bridge