### Paticipated rooms

GET http://43.203.222.95:8080/api/chat/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwidXNlcklkIjoxLCJpYXQiOjE3MTk3MjY3MTIsImV4cCI6MTcxOTgxMzExMn0.rTEfohH2WLWEhfZKPbvqO3xPLdbubRGXssSEF4ewsZg


### ChatHistory 100개

GET http://43.203.222.95:8080/api/chat/history?
    roomId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwidXNlcklkIjoxLCJpYXQiOjE3MTk3MjY3MTIsImV4cCI6MTcxOTgxMzExMn0.rTEfohH2WLWEhfZKPbvqO3xPLdbubRGXssSEF4ewsZg
