### Paticipated rooms

GET http://localhost:8080/api/chat/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwidXNlcklkIjoxLCJpYXQiOjE3MTk2MjQzNTQsImV4cCI6MTcxOTcxMDc1NH0.YBGSNDk182JUYXwxEgDYxTDrkqHu8NJaF3i-qVDnLRI


### ChatHistory 100개

GET http://localhost:8080/api/chat/history?
    roomId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwidXNlcklkIjoxLCJpYXQiOjE3MTk2MjQzNTQsImV4cCI6MTcxOTcxMDc1NH0.YBGSNDk182JUYXwxEgDYxTDrkqHu8NJaF3i-qVDnLRI
