version: "3.8"
services:
  rabbit1:
    image: rabbitmq:management
    container_name: rabbit1
    hostname: rabbit1
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh

  rabbit2:
    image: rabbitmq:management
    container_name: rabbit2
    hostname: rabbit2
    links:
      - rabbit1
    environment:
      - JOIN_CLUSTER_HOST=rabbit1
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh

  rabbit3:
    image: rabbitmq:management
    container_name: rabbit3
    hostname: rabbit3
    links:
      - rabbit1
      - rabbit2
    environment:
      - JOIN_CLUSTER_HOST=rabbit1
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh

  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbit1
      - rabbit2
      - rabbit3
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1936:1936"