version: "3.8"
services:
  kopring:
    restart: on-failure
    container_name: chat-kopring
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/chat
      - SPRING_DATASOURCE_USERNAME=jin
      - SPRING_DATASOURCE_PASSWORD=jin123
      - RABBITMQ_HOST=localhost
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=user
    depends_on:
      - mysql
      - haproxy

  mysql:
    image: mysql:latest
    container_name: mysql-chat
    environment:
      MYSQL_ROOT_PASSWORD: maiload
      MYSQL_DATABASE: chat
      MYSQL_USER: jin
      MYSQL_PASSWORD: jin123
    ports:
      - "3306:3306"
#    volumes:
#      - ./data/:/var/lib/mysql

  rabbit1:
    image: rabbitmq:management
    container_name: rabbit1
    hostname: rabbit1
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh

  rabbit2:
    image: rabbitmq:management
    container_name: rabbit2
    hostname: rabbit2
    links:
      - rabbit1
    environment:
      - JOIN_CLUSTER_HOST=rabbit1
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh

  rabbit3:
    image: rabbitmq:management
    container_name: rabbit3
    hostname: rabbit3
    links:
      - rabbit1
      - rabbit2
    environment:
      - JOIN_CLUSTER_HOST=rabbit1
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh

  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbit1
      - rabbit2
      - rabbit3
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1936:1936"