### Log in
GET http://localhost:8080/login

### Logout
GET http://localhost:8080/api/member/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaW4iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJ1c2VySWQiOjEsImlhdCI6MTcxNzU2MDM1MSwiZXhwIjoxNzE3NTYyMTUxfQ.qDv3hcm6HPdPC82fhW-HJrfChhqMHl0EKWZ7fTvuI20
Refresh: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaW4iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJ1c2VySWQiOjEsImV4cCI6MTcxNzY2ODM1MX0.v_BCzjJ8kFKXE58DlZml6mGh1fMn0j2tmbxTQ7UP4wU

### Reissue
GET http://localhost:8080/api/member/reissue-token
Refresh: yJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaW4iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJ1c2VySWQiOjEsImV4cCI6MTcxNzc2NTk0MH0.LvEPzYmD-if0FSbNxmLM4ZQkgAWliEmH--Tcu0kWPGE

### Sign up admin
POST http://localhost:8080/api/member/signup/admin
Content-Type: application/json

{
  "loginId": "admin",
  "password": "admin123!",
  "name": "관리자",
  "birthDate": "1996-10-24",
  "gender": "MAN",
  "email": "admin@email.com",
  "ceoName": "CEO",
  "companyName": "testCompany",
  "businessId": "1234567890",
  "companyCertificateNumber": "12345678901234"
}

### Sign up member
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "loginId": "jin",
  "password": "qwer123!",
  "name": "이정진",
  "birthDate": "1996-10-24",
  "gender": "MAN",
  "email": "jin@email.com"
}

### Log in admin
POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "loginId": "admin",
  "password": "admin123!"
}
### Log in member
POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "loginId": "jin",
  "password": "qwer123!"
}

### info

GET http://localhost:8080/api/member/info
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwidXNlcklkIjoxLCJpYXQiOjE3MTc5OTYyNzUsImV4cCI6MTcxODA4MjY3NX0.XROnnUkYFj1PAbgg5KlQrnxZYj1dU4zuH0DGD8ERxAs

### info memberList

GET http://localhost:8080/api/member/admin/info
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwidXNlcklkIjoxLCJpYXQiOjE3MTc5OTYyNzUsImV4cCI6MTcxODA4MjY3NX0.XROnnUkYFj1PAbgg5KlQrnxZYj1dU4zuH0DGD8ERxAs

### info update

PUT http://localhost:8080/api/member/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaW4iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJ1c2VySWQiOjIsImlhdCI6MTcxODAwMzIzMiwiZXhwIjoxNzE4MDg5NjMyfQ.4VbOR2zkeQAlfwcYNGQXKoyGFdcbKBMHv_smzObNX8w

{
  "id": 2,
  "loginId": "jin",
  "password": "qwer123!",
  "name": "JJ L",
  "birthDate": "2000-01-01",
  "gender": "MAN",
  "email": "maiload77@gmail.com",
  "companyCode": "1"
}

### state update

PUT http://localhost:8080/api/member/admin/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwidXNlcklkIjoxLCJpYXQiOjE3MTc5OTYyNzUsImV4cCI6MTcxODA4MjY3NX0.XROnnUkYFj1PAbgg5KlQrnxZYj1dU4zuH0DGD8ERxAs

{
  "id": 2,
  "loginId": "jin",
  "password": "jin123!!",
  "name": "이정진",
  "birthDate": "1996-10-24",
  "gender": "MAN",
  "email": "jin@email.com",
  "companyCode": "1",
  "state": "APPROVED"
}

### Approved colleague

GET http://localhost:8080/api/member/colleague
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwidXNlcklkIjoxLCJpYXQiOjE3MTc5OTYyNzUsImV4cCI6MTcxODA4MjY3NX0.XROnnUkYFj1PAbgg5KlQrnxZYj1dU4zuH0DGD8ERxAs


### NotJoined colleague

GET http://localhost:8080/api/member/colleague/notJoin?
    roomId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwidXNlcklkIjoxLCJpYXQiOjE3MTc5OTYyNzUsImV4cCI6MTcxODA4MjY3NX0.XROnnUkYFj1PAbgg5KlQrnxZYj1dU4zuH0DGD8ERxAs
