### Log in
GET http://localhost:8080/login

### Logout
GET http://localhost:8080/api/member/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaW4iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJ1c2VySWQiOjEsImlhdCI6MTcxNzU2MDM1MSwiZXhwIjoxNzE3NTYyMTUxfQ.qDv3hcm6HPdPC82fhW-HJrfChhqMHl0EKWZ7fTvuI20
Refresh: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaW4iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJ1c2VySWQiOjEsImV4cCI6MTcxNzY2ODM1MX0.v_BCzjJ8kFKXE58DlZml6mGh1fMn0j2tmbxTQ7UP4wU

### Reissue
GET http://localhost:8080/api/member/reissue-token
Refresh: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaW4iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJ1c2VySWQiOjEsImV4cCI6MTcxNzY2ODMxMX0.S1PWKmu73FFMyf5F-s-U9ex0FSEqbmYfXLN6hty5qFI

### Sign up
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "loginId": "jin",
  "password": "qwer123!",
  "name": "이정진",
  "birthDate": "1996-10-24",
  "gender": "MAN",
  "email": "jin@email.com"
}

### Log in
POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "loginId": "jin",
  "password": "qwer123!"
}

### info

GET http://localhost:8080/api/member/info
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaW4iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJ1c2VySWQiOjEsImlhdCI6MTcxNzU1ODkxNywiZXhwIjoxNzE3NTYwNzE3fQ.ZkziedpPelaRs8s6MKn1yMRUSEGJVE8QMw8TNBcpbCM

### info update

PUT http://localhost:8080/api/member/info
Content-Type: application/json
Authorization: Bearer

{
  "id": 1,
  "loginId": "maiload77@gmail.com",
  "password": "qwer123!",
  "name": "JJ L",
  "birthDate": "2000-01-01",
  "gender": "MAN",
  "email": "maiload77@gmail.com"
}

//{
//  "id": 1,
//  "loginId": "jin",
//  "password": "qwer123!",
//  "name": "이정진",
//  "birthDate": "2000-10-24",
//  "gender": "MAN",
//  "email": "jin@email.com"
//}